ALTER TABLE sales
ADD id_order_sale INT(11),	
ADD unit_price_sale TEXT,	
ADD commision_sale TEXT,	
ADD payment_method_sale TEXT,	
ADD id_payment_sale TEXT,	
ADD status_sale TEXT,	
ADD date_created_sale DATE,	
ADD date_updated_sale TIMESTAMP;
